<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Moq" Version="4.20.0" />
    <PackageReference Include="Shouldly" Version="4.2.0" />
    <PackageReference Include="xunit" Version="2.6.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\WebApiExample.Common\WebApiExample.Common.csproj" />
    <ProjectReference Include="..\WebApiExample.DataStore\WebApiExample.DataStore.csproj" />
    <ProjectReference Include="..\WebApiExample.WebApp\WebApiExample.WebApp.csproj" />
  </ItemGroup>
</Project>